/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author roveda
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    private TelaClientes tpclientes;
    private TelaFuncionario tpfunc;
    private TelaProdutora tpprod;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastroicone = new javax.swing.JMenu();
        menuclienteicone = new javax.swing.JMenuItem();
        mnfunc = new javax.swing.JMenuItem();
        mnprod = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPainelLayout = new javax.swing.GroupLayout(dskPainel);
        dskPainel.setLayout(dskPainelLayout);
        dskPainelLayout.setHorizontalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dskPainelLayout.setVerticalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        menucadastroicone.setText("Cadastros");

        menuclienteicone.setText("Clientes");
        menuclienteicone.addActionListener(this::menuclienteiconeActionPerformed);
        menucadastroicone.add(menuclienteicone);

        mnfunc.setText("Funcionarios");
        mnfunc.addActionListener(this::mnfuncActionPerformed);
        menucadastroicone.add(mnfunc);

        mnprod.setText("Produtoras");
        mnprod.addActionListener(this::mnprodActionPerformed);
        menucadastroicone.add(mnprod);

        jMenuBar1.add(menucadastroicone);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuclienteiconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclienteiconeActionPerformed

        if (tpclientes == null || tpclientes.isClosed()) {
            tpclientes = new TelaClientes();
            tpclientes.setVisible(true);
            dskPainel.add(tpclientes);
        }

 
    }//GEN-LAST:event_menuclienteiconeActionPerformed

    private void mnfuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnfuncActionPerformed
       if (tpfunc == null || tpfunc.isClosed()) {
            tpfunc = new TelaFuncionario();
            tpfunc.setVisible(true);
            dskPainel.add(tpfunc);
    }//GEN-LAST:event_mnfuncActionPerformed
    }
    private void mnprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnprodActionPerformed
       if (tpprod == null || tpprod.isClosed()) {
            tpprod = new TelaProdutora();
            tpprod.setVisible(true);
            dskPainel.add(tpprod);  // TODO add your handling code here:
    }//GEN-LAST:event_mnprodActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menucadastroicone;
    private javax.swing.JMenuItem menuclienteicone;
    private javax.swing.JMenuItem mnfunc;
    private javax.swing.JMenuItem mnprod;
    // End of variables declaration//GEN-END:variables
}
